# src/my_turtlebot3_controller/config/final_nav2_params.yaml
# This file provides a safe, default configuration for Nav2.

amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    transform_tolerance: 1.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    # This line is the key fix. It explicitly tells the bt_navigator to use a
    # standard behavior tree that does not require any special, missing plugins.
    default_bt_xml_filename: "$(find-pkg-share nav2_bt_navigator)/behavior_trees/navigate_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    # You can tune speed limits here later
    min_x_velocity: 0.0
    max_x_velocity: 0.26
    min_speed_xy: 0.0
    max_speed_xy: 0.26
    acc_lim_x: 2.5
    acc_lim_theta: 3.2

planner_server:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    # The launch file will provide the correct absolute path to this
    yaml_filename: "map.yaml"
