# This is the definitive, corrected parameter file for your project.
# It is configured for a non-namespaced robot running in simulation.

# Global parameters that are passed to all nodes
# This is where we set use_sim_time for everyone.
/**:
  ros__parameters:
    use_sim_time: True

amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    transform_tolerance: 1.0
    # This section makes startup automatic. No RViz click needed.
    initial_pose:
      x: -2.0
      y: -0.5
      z: 0.0
      yaw: 0.0

bt_navigator:
  ros__parameters:
    # This line is the KEY FIX. It forces Nav2 to use a standard behavior tree
    # and prevents the ".so" library loading errors.
    default_bt_xml_filename: "$(find-pkg-share nav2_bt_navigator)/behavior_trees/navigate_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # You can tune the robot's driving behavior here
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      # To reduce inflation, see the costmap sections below

planner_server:
  ros__parameters:
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

# Common costmap parameters
costmap_common:
  ros__parameters:
    robot_radius: 0.11 # Slightly larger than the actual robot for safety
    obstacle_layer:
      enabled: True
      observation_sources: scan
      scan:
        topic: /scan
        sensor_frame: base_scan
        observation_persistence: 0.0
        expected_update_rate: 0.0
        data_type: "LaserScan"
        clearing: True
        marking: True
    inflation_layer:
      cost_scaling_factor: 3.0
      inflation_radius: 0.35 # Decrease this to get closer to obstacles

global_costmap:
  ros__parameters:
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_footprint
    rolling_window: false
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      map_subscribe_transient_local: True

local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: base_footprint
    rolling_window: true
    width: 3
    height: 3
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]
